version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_tareas
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: tareas_db
    ports:
      - "3306:3306"

  gestion-tareas:
    image: gestion-tareas
    container_name: gestion_tareas
    depends_on:
      - mysql
    ports:
      - "8080:8080"